name: Template trello->gh-pages site

description: Work in progress

item: podcast

baseurl: file:///home/andy/Documents/trello-test/_site

headertitle: Banner for the test
headertext: Explanation and description of the test.

gtm-token: GTM-xxxxxx
social-media-handle: name
youtube-channel: UCxxxxxxxxxxxxxxxxx

collections:
  podcast:
    output: true

