name: Template trello->gh-pages site

description: Work in progress

item: podcast

baseurl: https://lazysoundsystem.github.io/trello-test

headertitle: Banner for the test
headertext: Explanation and description of the test.

gtm-token: GTM-xxxxxx
social-media-handle: name
youtube-channel: UCxxxxxxxxxxxxxxxxx

collections:
  podcast:
    output: true

